"""Changes in the models

Revision ID: fc462949ab5d
Revises: 
Create Date: 2024-05-16 17:33:50.111737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc462949ab5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('appointments', 'price',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'appointment_id')
    op.drop_column('users', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'patients', ['patient_id'], ['id'])
    op.create_foreign_key('users_ibfk_2', 'users', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('appointments', 'user_id')
    # ### end Alembic commands ###
